# Generated by Django 6.0.2 on 2026-03-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siotdm2app', '0006_alter_user_organization_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siotdm2app.organization'),
            preserve_default=False,
        ),
    ]
