# Generated by Django 6.0.2 on 2026-03-12 13:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siotdm2app', '0010_alter_devicedata_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='data_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]