# Generated by Django 6.0.2 on 2026-03-12 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siotdm2app', '0011_devicedata_id_alter_devicedata_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='data_id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False
            ),
        ),
    ]